# Test description:
#   This test simulates a busy network:
#   If we set up 4 routers, 2 edges and 2 clouds (the cloud router will forward the
#   messages from 1 to 2 and the edge will forward them to DomainParticipants), 12
#   best-effort publishers sending large messages (100kB, 200kB, 300kB, 400kB) to
#   3 best-effort subscribers on 3 different topics and one reliable publisher
#   sending messages to a reliable subscriber, at 10Hz. The test checks if all the
#   messages are forwarded from the reliable publisher to the reliable subscriber.
#
# Test architecture:

#  ┌───────────────────────────────────────────────────────────────┐
#  │ cloud_edge_net                                                │
#  │        ┌──────────────────┐         ┌──────────────────┐      │
#  │        │ ddsrouter_cloud_1◄─────────► ddsrouter_cloud_2│      │
#  │        │ (wan + wan)      │         │ (wan + wan)      │      │
#  │        └────────▲─────────┘         └────────┬─────────┘      │
#  │                 │                            │                │
#  │       ┌─────────┴──────────┐     ┌───────────▼────────┐       │
#  │       │  ddsrouter_edge_1  │     │  ddsrouter_edge_2  │       │
#  │       │                    │     │                    │       │
#  │       │  (edge_1_net+wan)  │     │  (edge_1_net+wan)  │       │
#  └───────┼────────────────────┼─────┼────────────────────┼───────┘
#  ┌───────┼────────────────────┼─┐ ┌─┼────────────────────┼───────┐
#  │       └───────────▲─▲─▲─▲──┘ │ │ └──┬─┬─┬─┬───────────┘       │
#  │                   │ │ │ │    │ │    │ │ │ │                   │
#  │  Domain 103       │ │ │ │    │ │    │ │ │ │       Domain  105 │
#  │ ┌───────────────┐ │ │ │ │    │ │    │ │ │ │                   │
#  │ │ publisher_1   │ │ │ │ │    │ │    │ │ │ │ ┌───────────────┐ │
#  │ │ ...           ├─┘ │ │ │    │ │    │ │ │ │ │ subscriber_1  │ │
#  │ │ publisher_4   │   │ │ │    │ │    │ │ │ └─► (edge_2_net)  │ │
#  │ │ (edge_1_net)  │   │ │ │    │ │    │ │ │   └───────────────┘ │
#  │ └───────────────┘   │ │ │    │ │    │ │ │                     │
#  │                     │ │ │    │ │    │ │ │   ┌───────────────┐ │
#  │ ┌───────────────┐   │ │ │    │ │    │ │ │   │ subscriber_2  │ │
#  │ │ publisher_5   │   │ │ │    │ │    │ │ └───► (edge_2_net)  │ │
#  │ │ ...           │   │ │ │    │ │    │ │     └───────────────┘ │
#  │ │ publisher_8   ├───┘ │ │    │ │    │ │                       │
#  │ │ (edge_1_net)  │     │ │    │ │    │ │     ┌───────────────┐ │
#  │ └───────────────┘     │ │    │ │    │ │     │ subscriber_3  │ │
#  │                       │ │    │ │    │ └─────► (edge_2_net)  │ │
#  │ ┌───────────────┐     │ │    │ │    │       └───────────────┘ │
#  │ │ publisher_9   │     │ │    │ │    │                         │
#  │ │ ...           │     │ │    │ │    │   ┌───────────────────┐ │
#  │ │ publisher_12  ├─────┘ │    │ │    │   │subscriber_reliable│ │
#  │ │ (edge_1_net)  │       │    │ │    └───► (edge_2_net)      │ │
#  │ └───────────────┘       │    │ │        └───────────────────┘ │
#  │                         │    │ │                              │
#  │ ┌──────────────────┐    │    │ │                              │
#  │ │publisher_reliable│    │    │ │                              │
#  │ │ (edge_1_net)     ├────┘    │ │                              │
#  │ └──────────────────┘         │ │                              │
#  └──────────────────────────────┘ └──────────────────────────────┘

services:

  # ROUTERS
  ddsrouter_cloud_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud_1
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 15

  ddsrouter_cloud_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud_2
    depends_on:
      - ddsrouter_cloud_1
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud_2.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 15

  ddsrouter_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_1
    depends_on:
      - ddsrouter_cloud_1
    networks:
      - cloud_edge_net
      - edge_1_net
    volumes:
      - ./ddsrouter_edge_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 15

  ddsrouter_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_2
    depends_on:
      - ddsrouter_cloud_2
    networks:
      - cloud_edge_net
      - edge_2_net
    volumes:
      - ./ddsrouter_edge_2.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 15

 # SUBSCRIBERS
  subscriber_reliable:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_reliable
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 10 --timeout 15 --args "--samples 10 --domain 105 --name LargeDataTopic_reliable --reliable"

  subscriber_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 10 --timeout 10 --allow-duplicates -1 --args "--samples 10 --domain 105 --name LargeDataTopic_1"

  subscriber_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 10 --timeout 10 --allow-duplicates -1 --args "--samples 10 --domain 105 --name LargeDataTopic_2"


  subscriber_3:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_3
    depends_on:
      - ddsrouter_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 10 --timeout 10 --allow-duplicates -1 --args "--samples 10 --domain 105 --name LargeDataTopic_3"

  # PUBLISHERS
  publisher_reliable:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_reliable
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 10 --msg-size 1 --domain 103 --name LargeDataTopic_reliable --reliable --wait 1

  publisher_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 100000 --domain 103 --name LargeDataTopic_1

  publisher_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_2
    depends_on:
      - ddsrouter_edge_1
    networks:
     - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 200000 --domain 103 --name LargeDataTopic_1

  publisher_3:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_3
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 300000 --domain 103 --name LargeDataTopic_1

  publisher_4:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_4
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 400000 --domain 103 --name LargeDataTopic_1

  publisher_5:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_5
    depends_on:
      - ddsrouter_edge_1
    networks:
     - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 100000 --domain 103 --name LargeDataTopic_2

  publisher_6:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_6
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 200000 --domain 103 --name LargeDataTopic_2

  publisher_7:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_7
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 300000 --domain 103 --name LargeDataTopic_2

  publisher_8:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_8
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 400000 --domain 103 --name LargeDataTopic_2

  publisher_9:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_9
    depends_on:
      - ddsrouter_edge_1
    networks:
     - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 100000 --domain 103 --name LargeDataTopic_3

  publisher_10:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_10
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 200000 --domain 103 --name LargeDataTopic_3

  publisher_11:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_11
    depends_on:
      - ddsrouter_edge_1
    networks:
     - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 300000 --domain 103 --name LargeDataTopic_3

  publisher_12:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_12
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 100 --msg-size 400000 --domain 103 --name LargeDataTopic_3


networks:
  edge_1_net:
  edge_2_net:
  cloud_edge_net:
  default:
    driver: none
