# Test description:
#   Check that tracks get rebuilt when a subscriber over WAN disconnects and reconnects.
#
# Test architecture:
#
# ┌─────────────────────────────────────────┐
# │  cloud_edge_net                         │
# │ ┌─────────────────┐ ┌─────────────────┐ │
# │ │ddsrouter_cloud_0│ │ddsrouter_cloud_1│ │
# │ │                ─┼─┤►                │ │
# │ │(wan + wan)      │ │(wan + wan)      │ │
# │ └──────────────▲──┘ └──────────────┬──┘ │
# │                │                   │    │
# │ ┌──────────────┼──┐ ┌──────────────┼──┐ │
# │ │  Domain 80   │  │ │  Domain 81   │  │ │
# │ │              │  │ │              │  │ │
# │ │  edge_0_net  │  │ │  edge_1_net  │  │ │
# │ │ ┌────────────┴┐ │ │ ┌────────────▼┐ │ │
# │ │ │ddsrouter_0  │ │ │ │ddsrouter_1  │ │ │
# │ │ │             │ │ │ │             │ │ │
# │ │ │(local + wan)│ │ │ │(local + wan)│ │ │
# │ │ └──────────▲──┘ │ │ └──────────┬──┘ │ │
# │ │            │    │ │            │    │ │
# └─┼────────────┼────┼─┼────────────┼────┼─┘
#   │            │    │ │            │    │
#   │ ┌──────────┴──┐ │ │ ┌──────────▼──┐ │
#   │ │publisher_t0 │ │ │ │subscriber_t0│ │
#   │ │             │ │ │ │             │ │
#   │ │(local)      │ │ │ │(local)      │ │
#   │ └─────────────┘ │ │ └─────────────┘ │
#   │                 │ │                 │
#   └─────────────────┘ └─────────────────┘

services:

  # CLOUD
  ddsrouter_cloud_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud_0
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud_0.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  ddsrouter_cloud_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud_1
    depends_on:
      - ddsrouter_cloud_0
    networks:
      - cloud_edge_net
    volumes:
      - ./ddsrouter_cloud_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  # DOMAIN 80
  ddsrouter_edge_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_0
    depends_on:
      - ddsrouter_cloud_0
    networks:
      - cloud_edge_net
      - edge_0_net
    volumes:
      - ./ddsrouter_edge_0.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  publisher_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0
    depends_on:
      - ddsrouter_edge_0
    networks:
      - edge_0_net
    command: install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample publisher --samples 110 --domain 80 --interval 100

  # DOMAIN 81
  ddsrouter_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_1
    depends_on:
      - ddsrouter_cloud_1
    networks:
      - cloud_edge_net
      - edge_1_net
    volumes:
      - ./ddsrouter_edge_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  subscriber_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 20 --timeout 8 --args "--samples 20 --domain 81"

  subscriber_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2
    depends_on:
      - ddsrouter_edge_1
    networks:
      - edge_1_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 20 --timeout 6 --delay 4 --args "--samples 20 --domain 81"

networks:
  edge_0_net:
  edge_1_net:
  cloud_edge_net:
  default:
    driver: none
