name: 'fetch-fastdds-repos'
description: 'Fetch Fast DDS and its dependencies'
runs:
  using: "composite"
  steps:
    - id: fetch-fastdds-repos
      run: |
        wget https://raw.githubusercontent.com/eProsima/Fast-DDS/master/fastrtps.repos
        vcs import src <  fastdds_statistics_backend.repos
      shell: bash
