# Test description:
#   This test checks simple communication (simple discovery and UDP) with partitions
#
# Test architecture:
#
#   Domain 0                                  Domain 1
# Publisher_0_0  (A)                        Publisher_1_0 (bbb;ccc)
# Subscriber_0_0 (bbb)
#                         <->  Router  <->
# Subscriber_2_0 (A)                        Subscriber_3_0 (*)
# Subscriber_2_1 (bbb)
# Subscriber_2_2 (ccc)
#   Domain 2                                  Domain 3

services:

  # ROUTER
  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - std_net
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  # DOMAIN 0
  pub_0_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: pub_0_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample publisher --interval 100 --samples 110 --domain 0 --partitions "A"

  sub_0_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_0_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: python3 /execute_and_validate_subscriber.py --exe install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample --samples 20 --timeout 12 --domain 0 --partitions "bbb"

  # DOMAIN 1
  pub_1_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: pub_1_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample publisher --interval 100 --samples 110 --domain 0 --partitions "bbb;ccc"

  # DOMAIN 2
  sub_2_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_2_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: python3 /execute_and_validate_subscriber.py --exe install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample --samples 20 --timeout 12 --domain 2 --partitions "A"

  sub_2_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_2_1
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: python3 /execute_and_validate_subscriber.py --exe install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample --samples 20 --timeout 12 --domain 2 --partitions "bbb"

  sub_2_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_2_2
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: python3 /execute_and_validate_subscriber.py --exe install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample --samples 20 --timeout 12 --domain 2 --partitions "ccc"

  # DOMAIN 3
  sub_3_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_3_0
    depends_on:
      - ddsrouter
    networks:
      - std_net
    command: python3 /execute_and_validate_subscriber.py --exe install/AdvanceConfigurationExample/examples/cpp/dds/AdvanceConfigurationExample/AdvanceConfigurationExample --samples 20 --timeout 12 --domain 2 --partitions "*"

networks:
  std_net:
  default:
    driver: none
