# Test description:
#   This test checks the repeater functionality of the DDS Router. A DDS Router is deployed in the cloud with a single
#   repeater participant, and we verify that the data sent from network 1 reaches network 2.
#
# Test architecture:
#
#          ┌────────────────────────────────┐  ┌────────────────────────────┐
#          │ cloud_edge_1_net               │  │           cloud_edge_2_net │
#          │                                │  │                            │
#          │                        ┌───────┴──┴───────┐                    │
#          │                        │ ddsrouter_cloud  │                    │
#          │                        │ (wan [repeater]) │                    │
#          │                        └─▲──────┬──┬──────┘                    │
#          │                          │      │  │    │                      │
#          │           ┌──────────────┘      │  │    └─────────┐            │
#   ┌──────┼───────────┼──────────────────┐  │  │  ┌───────────┼────────────┼──────┐
#   │      │           │                  │  │  │  │           │            │      │
#   │      │ ┌──────────────────┐         │  │  │  │   ┌───────▼──────────┐ │      │
#   │      │ │ ddsrouter_edge_1 │         │  │  │  │   │ ddsrouter_edge_2 │ │      │
#   │      │ │ (local + wan)    │         │  │  │  │   │ (local + wan)    │ │      │
#   │      │ └────────────▲─────┘         │  │  │  │   └───────┬──────────┘ │      │
#   │      │              │               │  │  │  │           │            │      │
#   │      └──────────────┼───────────────┼──┘  └──┼───────────┼────────────┘      │
#   │                     │               │        │           │                   │
#   │                    ┌┴───────────┐   │        │    ┌──────▼───────┐           │
#   │                    │ pub_edge_1 │   │        │    │ sub_edge_2   │           │
#   │                    │ (publisher)│   │        │    │ (subscriber) │           │
#   │                    └────────────┘   │        │    └──────────────┘           │
#   │                                     │        │                               │
#   │ edge_1_net                          │        │                    edge_2_net │
#   └─────────────────────────────────────┘        └───────────────────────────────┘

services:

  ddsrouter_cloud:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_cloud
    networks:
      cloud_edge_1_net:
        aliases:
            - ddsrouter_cloud.edge_1
      cloud_edge_2_net:
        aliases:
            - ddsrouter_cloud.edge_2
    volumes:
      - ./ddsrouter_cloud.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  ddsrouter_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_1
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_1_net
      - edge_1_net
    volumes:
      - ./ddsrouter_edge_1.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  pub_edge_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: pub_edge_1
    networks:
      - edge_1_net
    command: install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample publisher -i 100 -s 110

  ddsrouter_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter_edge_2
    depends_on:
      - ddsrouter_cloud
    networks:
      - cloud_edge_2_net
      - edge_2_net
    volumes:
      - ./ddsrouter_edge_2.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 12

  sub_edge_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: sub_edge_2
    networks:
      - edge_2_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/BasicConfigurationExample/examples/cpp/dds/BasicConfigurationExample/BasicConfigurationExample --samples 20 --timeout 12 --args "--samples 20"

networks:
  edge_1_net:
  edge_2_net:
  cloud_edge_1_net:
  cloud_edge_2_net:
  default:
    driver: none
