
#################################
# Topics Allowed

allowlist:
  [
    {name: "HelloWorldTopic", type: "HelloWorld"},
  ]

#################################
# Simple Participant in domain 0

local:
  domain: 0

#################################
# WAN Participant

wan:
  listening-addresses:
    [
      {
        ip: "2.2.2.2",
        port: 11666,
      }
    ]
