FROM ubuntu-vulcanexus:galactic

# Install demo-nodes-cpp
RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    source /vulcanexus_ws/install/setup.bash && \
    apt update && \
    apt install -y ros-$ROS_DISTRO-demo-nodes-cpp

COPY ./run.bash /
RUN chmod +x /run.bash

# Setup entrypoint
ENTRYPOINT ["/run.bash"]
