name: Run colcon test in ubuntu
description: Run colcon test in ubuntu for a specific package
inputs:
  package_name:
    description: 'Specifies the package to run the tests'
    required: true
runs:
  using: composite
  steps:
  - run: |
      source install/setup.bash
      colcon test \
        --packages-select ${{ inputs.package_name }} \
        --event-handlers=console_direct+ \
        --return-code-on-test-failure \
        --ctest-args \
          --label-exclude xfail \
          --timeout 60
    shell: bash
