name: 'fetch-fastdds-repos'
description: 'Fetch Fast DDS and its dependencies'
inputs:
  fastdds_branch:
    description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
    required: true
    default: 'master'
runs:
  using: "composite"
  steps:
    - id: fetch-fastdds-repos
      run: |
        wget https://raw.githubusercontent.com/eProsima/Fast-DDS/master/fastrtps.repos
        vcs import src <  fastrtps.repos
        cd src/fastrtps && git checkout ${{ inputs.fastdds_branch }} && cd ../..
      shell: bash
