# Test description:
#   This test checks simple communication (simple discovery and UDP) with DDS(xml) and RTPS(local) participants.
#
# Test architecture:
#  topic0 -> non reliable
#  topic1 -> reliable transient_local
#
#   Domain 0         <-->  Router  <-->     Domain 1
# publisher_t0_0_0                        subscriber_t0_1_0
# subscriber_t1_0_0                       publisher_t1_1_0
#
# NOTE:
#   Subscribers transient do not need to receive everything, but to received from 0 to N.
#   This is because last message of Publisher cannot assure that exists before closing Pub.
#
#   DDS Router has a delay to start, so to test transient local in router.
#   sleep command is use for this
#

services:

  # ROUTER
  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - std_net
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: bash -c "sleep 1 && source /ddsrouter/install/setup.bash && ddsrouter -c /config.yaml --timeout 12"

  # DOMAIN 0
  publisher_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_t0
    networks:
      - std_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 110 --domain 0 --name topic0

  subscriber_t1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_t1
    networks:
      - std_net
    volumes:
      - ../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --transient-local --delay 2 --exe build/fastdds_configuration_example/configuration --samples 50 --timeout 11 --args "--samples 50 --domain 0 --name topic1 --reliable --transient-local --keep-all"

  # DOMAIN 1
  subscriber_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_t0
    networks:
      - std_net
    volumes:
      - ../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 20 --timeout 12 --args "--samples 20 --domain 1 --name topic0"

  publisher_t1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_t1
    networks:
      - std_net
    command: build/fastdds_configuration_example/configuration publisher --interval 100 --samples 110 --domain 1 --reliable --transient-local --keep-all --name topic1

networks:
  std_net:
  default:
    driver: none
