## DATABROKER CONFIGURATION
interactive: false

time: 0

whitelist: []

## DATABROKER PARTICIPANT WAN CONFIGURATION
server-id: 0

listening-addresses:
  [
    {
      ip: "127.0.0.1",
      port: 11800
    }
  ]

connection-addresses: []

udp: false

# Inactive by default
# tls:
#   private_key: "pk.pem"
#   password: "password"
#   dh: "dh.pem"
#   ca: "ca.pem"
#   verify_ca: "ca.pem"

## DATABROKER PARTICIPANT LOCAL CONFIGURATION
ros: false

domain: 0
