name: 'install-apt-packages'
description: 'Install necessary apt packages'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update && sudo apt -y install \
          clang-tidy \
          curl \
          grep \
          libasio-dev \
          libtinyxml2-dev \
          libyaml-cpp-dev \
          python3 \
          python3-pip \
          python3-venv \
          software-properties-common \
          wget
      shell: bash
