name: 'install-apt-packages'
description: 'Install necessary apt packages'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update && sudo apt -y install \
          python3 \
          python3-pip \
          python3-venv \
          software-properties-common \
          wget \
          libasio-dev \
          libtinyxml2-dev \
          clang-tidy \
          curl \
          grep
      shell: bash
