# Test description:
#   This test checks that if we set up a router with Topic QoS configured globally and
#   at the participant and topic levels, the topic level prevails over the participant
#   level and the participant level pravails over the specs level.
#
# Test architecture:
#
#                                                         ┌───────────────┐
#                                                         │subscriber_1_t0│
#                                                         │               │
#                                        ┌────────────────►(local)        │
#                                        │   topic_0 5 Hz └───────────────┘
#                                        │
# ┌──────────────┐                       │                ┌───────────────┐
# │publisher_0_t0│                       │                │subscriber_1_t1│
# │              │                       │                │               │
# │(local)       │                       │                │(local)        │
# └────────────┬─┘                       │                └─▲─────────────┘
#              │   topic_0 10 Hz ┌───────┴─┐ topic_1 10 Hz  │
#              └─────────────────►ddsrouter├────────────────┘
#                                │         │
#              ┌─────────────────►(local)  ├────────────────┐
#              │   topic_1 10 Hz └───────┬─┘ topic_0 5 Hz   │
# ┌────────────┴─┐                       │                ┌─▼─────────────┐
# │publisher_0_t1│                       │                │subscriber_2_t0│
# │              │                       │                │               │
# │(local)       │                       │                │(local)        │
# └──────────────┘                       │                └───────────────┘
#                                        │
#                                        │   topic_1 5 Hz ┌───────────────┐
#                                        └────────────────►subscriber_2_t1│
#                                                         │               │
#                                                         │(local)        │
#                                                         └───────────────┘

services:

  # ROUTER
  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - std_net
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 8

  # DOMAIN 0
  publisher_0_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0_t0
    networks:
      - std_net
    command: install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample publisher --interval 100 --samples 80 --domain 80 --topic topic_0

  publisher_0_t1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0_t1
    networks:
      - std_net
    command: install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample publisher --interval 100 --samples 80 --domain 80 --topic topic_1

  # DOMAIN 1
  subscriber_1_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1_t0
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 81 --topic topic_0"

  subscriber_1_t1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1_t1
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 40 --timeout 8 --min-time 4 --args "--samples 40 --domain 81 --topic topic_1"

  # DOMAIN 2
  subscriber_2_t0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2_t0
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 82 --topic topic_0"

  subscriber_2_t1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2_t1
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe install/AdvancedConfigurationExample/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationExample --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 82 --topic topic_1"

networks:
  std_net:
  default:
    driver: none
