name: Install Fast CDR
description: Install and setup Fast CDR for linking and building application in Windows
inputs:
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
runs:
  using: composite
  steps:
  - run: >
      git clone https://github.com/eProsima/Fast-CDR.git;
      cmake -Ax64 -T host=x64 -B build\fastcdr Fast-CDR;
      cmake --build build\fastcdr --config ${{ inputs.cmake_build_type }} --target install
    shell: pwsh
