# Test description:
#   This test checks that if we set up a router that has two participants with two
#   different max-tx-rates configured, the subscribers connected to these participants
#   receive the messages at the max-tx-rate specified in the participant they are
#   connected to.
#
# Test architecture:
#                                     topic_0 10 Hz┌────────────┐
#                                   ┌──────────────►subscriber_1│
#                                   │              │            │
# ┌───────────┐             ┌───────┴─┐            │(local)     │
# │publisher_0│topic_0 20 Hz│ddsrouter│            └────────────┘
# │           ├─────────────►         │
# │(local)    │             │(local)  │            ┌────────────┐
# └───────────┘             └───────┬─┘            │subscriber_2│
#                                   │  topic_0 5 Hz│            │
#                                   └──────────────►(local)     │
#                                                  └────────────┘

services:

  # ROUTER
  ddsrouter:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsrouter
    networks:
      - std_net
    volumes:
      - ./ddsrouter.yaml:/config.yaml
    command: ddsrouter -c /config.yaml --timeout 8

  # DOMAIN 0
  publisher_0:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: publisher_0
    networks:
      - std_net
    command: build/fastdds_configuration_example/configuration publisher --interval 50 --samples 160 --domain 80 --name topic_0

  # DOMAIN 1
  subscriber_1:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_1
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 20 --timeout 8 --min-time 2 --args "--samples 20 --domain 81 --name topic_0"

  # DOMAIN 2
  subscriber_2:
    image: ${DDSROUTER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: subscriber_2
    networks:
      - std_net
    volumes:
      - ../../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_subscriber.py --exe build/fastdds_configuration_example/configuration --samples 20 --timeout 8 --min-time 4 --args "--samples 20 --domain 82 --name topic_0"

networks:
  std_net:
  default:
    driver: none
