name: Install eProsima dependencies
description: Install and setup foonatham-memory, Fast CDR and Fast DDS for linking and building applications in Windows
inputs:
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
  fastdds_branch:
    description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
    required: true
    default: 'master'
  utils_branch:
    description: 'Branch or tag of Dev Utils repository (https://github.com/eProsima/dev-utils)'
    required: true
    default: 'main'
runs:
  using: composite
  steps:
    - name: Install foonatham memory
      shell: pwsh
      run: >
        git clone --recurse-submodules --branch v0.6-2 https://github.com/foonathan/memory.git;
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DBUILD_SHARED_LIBS=OFF -DFOONATHAN_MEMORY_BUILD_TOOLS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON `
          -DFOONATHAN_MEMORY_BUILD_TESTS=OFF -Ax64 -T host=x64 -B build\memory memory;
        cmake --build build\memory --config ${{ inputs.cmake_build_type }} --target install

    - name: Install Fast CDR
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/Fast-CDR.git;
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -Ax64 -T host=x64 -B build\fastcdr Fast-CDR;
        cmake --build build\fastcdr --config ${{ inputs.cmake_build_type }} --target install

    - name: Install Fast DDS
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/Fast-DDS.git --branch ${{ inputs.fastdds_branch }};
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -DTHIRDPARTY=ON -DSECURITY=ON -DCOMPILE_EXAMPLES=OFF -DEPROSIMA_BUILD_TESTS=OFF `
          -DINTERNAL_DEBUG=ON -Ax64 -T host=x64 -B build\fastdds Fast-DDS;
        cmake --build build\fastdds --config ${{ inputs.cmake_build_type }} --target install

    # This is needed for windows 2019 to use /Zc:preprocessor to use c++ std preprocessor for ENUMERATION_BUILDER
    # due to a windows 2019 SDK non bug
    - name: Set environment variables for Windows 2019 build
      shell: pwsh
      run: >
        echo ("W2019_CMAKE_EXTRA_ARGS=-DCMAKE_SYSTEM_VERSION=10.0.19041.0") >> $env:GITHUB_ENV
      if: contains( matrix.windows-version , '2019')

    - name: Install Dev Utils
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/dev-utils.git --branch ${{ inputs.utils_branch }};
        cmake `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -DCMAKE_CXX_FLAGS="/WX /EHsc" `
          -Ax64 -T host=x64 `
          -B build\cmake_utils -S dev-utils\cmake_utils;
        cmake --build build\cmake_utils --config ${{ inputs.cmake_build_type }} --target install;
        cmake `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -DCMAKE_CXX_FLAGS="/WX /EHsc" `
          ${{ env.W2019_CMAKE_EXTRA_ARGS }} `
          -Ax64 -T host=x64 `
          -B build\cpp_utils -S dev-utils\cpp_utils;
        cmake --build build\cpp_utils --config ${{ inputs.cmake_build_type }} --target install;
