name: build_fastdds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        cmake-config:
          - 'Release'
          - 'Debug'
        windows-version:
          - 'windows-2019'
          - 'windows-2022'
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:
      - name: Sync eProsima/DDS-Router repository
        uses: actions/checkout@v2
        with:
          path: DDS-Router

      - name: Install OpenSSL
        uses: ./DDS-Router/.github/actions/install-openssl-windows

      - name: Install eProsima dependencies
        uses: ./DDS-Router/.github/actions/install-eprosima-dependencies-windows
        with:
          cmake_build_type: ${{ matrix.cmake-config }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.windows-version }}_${{ matrix.cmake-config }}_fastdds_install
          path: ${{ github.workspace }}\eprosima\install

  ubuntu-build:
    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'

    steps:
      - name: Sync eProsima/DDS-Router repository
        uses: actions/checkout@v2
        with:
          path: src/DDS-Router

      - name: Avoid DDS Router build
        run: |
          touch ./src/DDS-Router/COLCON_IGNORE

      - name: Install apt packages
        uses: ./src/DDS-Router/.github/actions/install-apt-packages

      - name: Install Python packages
        uses: ./src/DDS-Router/.github/actions/install-python-packages

      - name: Fetch Fast DDS repositories
        uses: ./src/DDS-Router/.github/actions/fetch-fastdds-repos

      - name: Build workspace
        run: |
          colcon build --event-handlers=console_direct+

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ubuntu-version }}_fastdds_install
          path: install
